// Code generated by protoc-gen-go.
// source: github.com/hailooss/ldap-service/proto/login/login.proto
// DO NOT EDIT!

/*
Package com_hailooss_service_ldap_login is a generated protocol buffer package.

It is generated from these files:
	github.com/hailooss/ldap-service/proto/login/login.proto

It has these top-level messages:
	Request
	Response
*/
package com_hailooss_service_ldap_login

import proto "github.com/hailooss/protobuf/proto"
import json "encoding/json"
import math "math"
import com_hailooss_service_ldap "github.com/hailooss/ldap-service/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Request struct {
	Username         *string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password         *string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

func (m *Request) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *Request) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

type Response struct {
	User             *com_hailooss_service_ldap.User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

func (m *Response) GetUser() *com_hailooss_service_ldap.User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
}
